version: '3'
services:
  test-db:
    image: postgres:16.2-alpine
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpwd
      - POSTGRES_DB=authentication

  test-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6382:6379'

volumes:
  pg-data:
  pgadmin-data:
