import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/registry';

import '@/scss/global.scss';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ReduxProvider from '@/components/shared/ReduxProvider';

import FavIcon from '../../../public/favicon.ico';
import TopBar from '../../components/shared/SwitchLanguages';
import { notFound } from 'next/navigation';
import { routing } from '../../i18n/routing';

export const metadata: Metadata = {
  title: 'NASK',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: FavIcon.src }],
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <StyledComponentsRegistry>
            <ReduxProvider>
              <div className="page-container">
                <TopBar />
                <Navbar />
                <div className="contain-wrap">{children}</div>
                <Footer />
              </div>
            </ReduxProvider>
          </StyledComponentsRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
