version: '3.9'

services:
  db:
    container_name: catalog_db
    image: mariadb:10
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: catalogdb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
